version: "3"
services:
  db:
    image: "postgres"
    container_name: "localpg"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - "5432:5432"
    volumes:
      - ./migration/createDB.sql:/docker-entrypoint-initdb.d/createDB.sql

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "quesia@email.com"
      PGADMIN_DEFAULT_PASSWORD: "1234"
    ports:
      - "54321:80"
    depends_on:
      - db